### ISSUE TITLE
Inference on custom RTDETR network

### ISSUE THREAD

**Issue by immohan6598** [olibartfast/object-detection-inference#8]
Hi, 

Thanks for sharing a work!

I  have trained a custom model using https://github.com/lyuwenyu/RT-DETR/tree/main/rtdetr_pytorch

network dimension is 1024 x 1024 and converted the .pt to tensorrt engine.

when i inference i get segmentation fault in the postprocessing 

![image](https://github.com/olibartfast/object-detection-inference/assets/89785217/6eafd112-b2a3-47a5-82cf-97e98bea0607)

i only have 15 classes

please help me figure out this

**Comment by olibartfast** [comment]
Hi there,
 In my project I used a pre-trained RT-DETR from [ultralytics](https://docs.ultralytics.com/models/rtdetr/) so the network output layer might be different from your model. Also I used 640x640 hardcoded input, I should modify my project to make it work for any size (maybe specifying it from cli).  

Which RT-DETR did you use from [lyuwenyu model zoo](https://github.com/lyuwenyu/RT-DETR/tree/main/rtdetr_pytorch#model-zoo)?  

What did you use to convert the binary to tensorrt engine, trtexec after onnx conversion or torch2trt?

**Comment by mohanrobro** [comment]
Hi, 
Thanks for the answer.
I used this official repo https://github.com/lyuwenyu/RT-DETR/tree/main/rtdetr_pytorch
Guideline is also available to convert a model to tensor-rt

I changed the hard-coded network dimension values.

I used this mode rtdetr_r18vd

I visualized the onnx model the output. I don't have that deep understanding on infer() function that updates ouputs_ and shapes_
so just want to understand.

I assume the infer will give the final output layer data.

Thanks in Advance.

**Comment by olibartfast** [comment]
Thanks all right, I'll take a look at it as soon as I can 👍

**Comment by immohan6598** [comment]
![image](https://github.com/olibartfast/object-detection-inference/assets/89785217/6f92fdd5-c1c3-4022-8762-476d9db93e1a)

output layer dimension

**Comment by olibartfast** [comment]
Yes is a completely different input/output format to the model I used for this project.

![Screenshot from 2024-01-31 19-52-41](https://github.com/olibartfast/object-detection-inference/assets/15491437/f2794258-b39a-4510-bb34-a94e2f993bff)

**Comment by immohan6598** [comment]
will you be able to support?
do you work on freelancing projects? I am working with freelancers to finish projects

**Comment by olibartfast** [comment]
Yes but not too soon, I have a full-time job so I can work on my GitHub projects only in my spare time.
